#!/usr/bin/env bash
# アプリアイコンとメニューバー用アイコンを、1 つのマスター資産から再生成する。
#
#   マスター: assets/icon/mark.svg   … 筆の一画（黒）。**形の正はこの 1 本だけ**
#             assets/icon/openshoki.icon/icon.json … レイヤー構成・背景・質感
#             assets/icon/openshoki.icon/Assets/seal.svg … 落款（一画とは別の形）
#   生成物:   assets/icon/openshoki.icon/Assets/mark-ink.svg        … 一画（墨・ライト用）
#             assets/icon/openshoki.icon/Assets/mark-ink-on-dark.svg … 一画（白・ダーク用）
#             assets/icon/generated/Assets.car     … macOS 26（Tahoe）のレイヤードアイコン
#             assets/icon/generated/openshoki.icns … 旧 macOS 用のフォールバック
#             assets/icon/tray.png                 … メニューバー常駐アイコン（36x36 8bit RGBA）
#
# 生成物はコミットする（ビルド時生成にしない）。`src/tray.rs` は tray.png を include_bytes! で
# 埋め込むため、資産を変えたらこのスクリプトを実行して差分をコミットすること。
#
# 必要なツール: Xcode（xcrun actool）、rsvg-convert、magick（ImageMagick）
set -euo pipefail

# --skip-appicon: actool を使う工程（Assets.car / .icns）を飛ばし、決定的に再現できる生成物
# （.icon の色違いレイヤーと tray.png）だけを作り直す。マスターと生成物のズレを検査したいとき
# （`scripts/check-icons.sh`）に使う。Assets.car は入力が同じでも毎回バイト列が変わるため。
# --out-dir DIR: 生成物をリポジトリではなく DIR 配下（同じ相対パス）へ書き出す。作業ツリーを
# 汚さずに再生成して比べたいときに使う。
skip_appicon=false
out_root=""
while [ $# -gt 0 ]; do
  case "$1" in
    --skip-appicon) skip_appicon=true; shift ;;
    --out-dir)
      if [ $# -lt 2 ]; then
        echo "--out-dir requires a directory" >&2
        exit 1
      fi
      # 呼び出し元の cwd 基準で解釈する（この後 repo_root へ cd するため、相対のままだと
      # リポジトリ内に書いてしまう）。
      mkdir -p "$2"
      out_root="$(cd "$2" && pwd)"
      shift 2 ;;
    *) echo "Unknown option: $1 (usage: $0 [--skip-appicon] [--out-dir DIR])" >&2; exit 1 ;;
  esac
done

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"
# --out-dir が無ければリポジトリへ書く。以降は絶対パスで統一する（「リポジトリへ書いたか」を
# 出力先の比較だけで判定できるようにする）。
out_root="${out_root:-$repo_root}"

icon_master="assets/icon/openshoki.icon"
mark_svg="assets/icon/mark.svg"
generated_dir="assets/icon/generated"
tray_png="assets/icon/tray.png"

# 出力先（--out-dir を付けるとリポジトリ外の同じ相対パスへ出す）。
layers_out="$out_root/$icon_master/Assets"
generated_out="$out_root/$generated_dir"
tray_out="$out_root/$tray_png"
mkdir -p "$layers_out" "$(dirname "$tray_out")"

# 一画の色違い（.icon のレイヤー）。形は mark.svg 1 本に集約し、色だけを差し替えて生成する
# （3 つの SVG に同じパスを複製すると、形を変えたときにアプリアイコンとメニューバーがずれる）。
ink_color="#16130F"
ink_on_dark_color="#F5F2EC"

# トレイアイコンの一辺（px）。tray-icon の macOS 実装は表示高さを 18pt に固定してアスペクト比
# だけ保つため、Retina の 2x にあたる 36px で作る（32px だと拡大されてぼやける）。
tray_size=36
# グリフの周りに残す余白（px）。0 にすると端が切れて見えるため、上下左右に少しだけ残す。
tray_margin=1

for tool in rsvg-convert magick; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "Missing required tool: $tool" >&2
    exit 1
  fi
done
# actool は アプリアイコンを作るときだけ必要（--skip-appicon は Xcode 無しでも走る）。
if [ "$skip_appicon" = false ] && ! xcrun --find actool >/dev/null 2>&1; then
  echo "Missing required tool: actool (install Xcode, or pass --skip-appicon)" >&2
  exit 1
fi

# mark.svg の塗り（黒）を各アピアランス用の色へ差し替えて .icon のレイヤーを作る。
# マスターのコメント（「形の正はこのファイル」）は落とす: 生成物に残ると「編集するな」と
# 矛盾したことを言うファイルになる。
generate_mark_layer() {
  local out="$1" color="$2"
  local tmp="$tmp_dir/$(basename "$out")"
  {
    echo "<!-- Generated by scripts/generate-icons.sh from $mark_svg. Do not edit. -->"
    # 先頭のコメントブロック（<svg より前）だけを落とす。行範囲で全体から消すと、
    # マスターの書き方次第で SVG の中身まで巻き込んで壊れる。
    sed -e '1,/<svg/{/<!--/,/-->/d;}' -e "s/fill=\"#000000\"/fill=\"$color\"/g" "$mark_svg"
  } > "$tmp"
  # 置換漏れ（マスターの書き方が変わった・複数パスの一部だけ黒が残った等）は、そのレイヤーが
  # ダークで沈む原因になる。色が入ったことと、黒が残っていないことの両方を確かめる。
  if ! grep -q "fill=\"$color\"" "$tmp" || grep -q 'fill="#000000"' "$tmp"; then
    echo "Failed to recolor $mark_svg to $color (is every fill written as fill=\"#000000\"?)" >&2
    exit 1
  fi
  # SVG として本当に読めるかを確かめる。コメント削除はマスターの書き方（コメント内に <svg と
  # 書く等）次第で中身を巻き込みうるので、タグの有無を見るだけでは足りない。
  local parse_error
  if ! parse_error="$(rsvg-convert "$tmp" -o "$tmp_dir/validate.png" 2>&1)"; then
    echo "Generated $out is not valid SVG: $parse_error" >&2
    echo "  (the leading comment block of $mark_svg is stripped before recoloring;" >&2
    echo "   writing <svg inside that comment breaks the stripping)" >&2
    exit 1
  fi
  mv "$tmp" "$out"
}

tmp_dir="$(mktemp -d -t openshoki-icons-XXXXXX)"
trap 'rm -rf "$tmp_dir"' EXIT

echo "Generating the stroke layers from $mark_svg"
generate_mark_layer "$layers_out/mark-ink.svg" "$ink_color"
generate_mark_layer "$layers_out/mark-ink-on-dark.svg" "$ink_on_dark_color"

if [ "$skip_appicon" = true ]; then
  echo "Skipping $generated_out (--skip-appicon)"
else
  echo "Generating $generated_out from $icon_master"
  # actool は .icon から Tahoe 用の Assets.car と旧 macOS 用の .icns を同時に書き出す。
  # .icns を ictool で直接書き出すと Tahoe 規定の余白が入らず大きすぎる見た目になるため、
  # 必ず actool 経由で作る。まず一時ディレクトリへ出し、成功したときだけ差し替える
  # （失敗してコミット済みの生成物が消えた状態を残さない）。
  # actool には「いま生成したレイヤー」を渡す。マスターの .icon をそのまま渡すと、--out-dir を
  # 使ったときにリポジトリ側の古いレイヤーからアプリアイコンが作られてしまう。
  # ディレクトリ名は --app-icon の名前と一致させる必要があるため openshoki.icon にする。
  staged="$tmp_dir/openshoki.icon"
  mkdir -p "$staged" "$tmp_dir/appicon"
  # マスターを丸ごと複製してから、いま生成したレイヤーで上書きする（中身を列挙すると、
  # .icon にレイヤーを足したときにコピー漏れで actool が謎のエラーになる）。
  cp -R "$icon_master/." "$staged/"
  cp "$layers_out/mark-ink.svg" "$layers_out/mark-ink-on-dark.svg" "$staged/Assets/"
  xcrun actool "$staged" --compile "$tmp_dir/appicon" \
    --output-format human-readable-text --notices --warnings --errors \
    --output-partial-info-plist /dev/null \
    --app-icon openshoki --include-all-app-icons \
    --enable-on-demand-resources NO --development-region en \
    --target-device mac --minimum-deployment-target 13.0 --platform macosx
  mkdir -p "$generated_out"
  # ファイル単位で差し替える（生成物は常にこの 2 つ。先にディレクトリを消すと、cp が失敗した
  # ときにコミット済みの生成物が消えたまま残る）。
  mv "$tmp_dir/appicon/Assets.car" "$tmp_dir/appicon/openshoki.icns" "$generated_out/"
fi

echo "Generating $tray_out from $mark_svg"
tmp_png="$tmp_dir/mark.png"
rsvg-convert -w 1024 -h 1024 "$mark_svg" -o "$tmp_png"
# 余白をトリムしてから 36x36 の中へ収める（縦横どちらが長くてもはみ出させない）。RGB は黒のまま
# 出す: 待機中は template 画像としてアルファだけが使われ、録音中は Rust 側（`tinted_glyph`）が
# 塗り替えるため、素材の色は問わない。形式は 8bit RGBA（`decode_rgba_png` が要求する）。
tmp_tray="$tmp_dir/tray.png"
magick "$tmp_png" -trim +repage \
  -resize "$((tray_size - tray_margin * 2))x$((tray_size - tray_margin * 2))" \
  -background none -gravity center -extent "${tray_size}x${tray_size}" \
  -define png:color-type=6 -strip "$tmp_tray"
mv "$tmp_tray" "$tray_out"

echo "Done:"
if [ "$skip_appicon" = false ]; then
  ls -1 "$generated_out" | sed 's/^/  /'
fi
echo "  $tray_out ($(magick identify -format '%wx%h %[bit-depth]bit %[channels]' "$tray_out"))"
if [ "$skip_appicon" = false ] && [ "$out_root" = "$repo_root" ]; then
  # actool の Assets.car は入力が同じでも毎回バイト列が変わる（実測）。マスターを変えていない
  # のに差分が出たときは戻してよい、と分かるようにしておく。
  echo
  echo "Note: Assets.car changes on every run even with identical input."
  echo "      If you did not change the master, restore it with:"
  echo "      git checkout -- $generated_dir/Assets.car"
fi
