#!/usr/bin/env bash
# アプリアイコンとメニューバー用アイコンを、1 つのマスター資産から再生成する。
#
#   マスター: assets/icon/mark.svg   … 筆の一画（黒）。**形の正はこの 1 本だけ**
#             assets/icon/openshoki.icon/icon.json … レイヤー構成・背景・質感
#             assets/icon/openshoki.icon/Assets/seal.svg … 落款（一画とは別の形）
#   生成物:   assets/icon/openshoki.icon/Assets/mark-ink.svg        … 一画（墨・ライト用）
#             assets/icon/openshoki.icon/Assets/mark-ink-on-dark.svg … 一画（白・ダーク用）
#             assets/icon/generated/Assets.car     … macOS 26（Tahoe）のレイヤードアイコン
#             assets/icon/generated/openshoki.icns … 旧 macOS 用のフォールバック
#             assets/icon/tray.png                 … メニューバー常駐アイコン（36x36 8bit RGBA）
#
# 生成物はコミットする（ビルド時生成にしない）。`src/tray.rs` は tray.png を include_bytes! で
# 埋め込むため、資産を変えたらこのスクリプトを実行して差分をコミットすること。
#
# 必要なツール: Xcode（xcrun actool）、rsvg-convert、magick（ImageMagick）
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

icon_master="assets/icon/openshoki.icon"
mark_svg="assets/icon/mark.svg"
generated_dir="assets/icon/generated"
tray_png="assets/icon/tray.png"

# 一画の色違い（.icon のレイヤー）。形は mark.svg 1 本に集約し、色だけを差し替えて生成する
# （3 つの SVG に同じパスを複製すると、形を変えたときにアプリアイコンとメニューバーがずれる）。
ink_color="#16130F"
ink_on_dark_color="#F5F2EC"

# トレイアイコンの一辺（px）。tray-icon の macOS 実装は表示高さを 18pt に固定してアスペクト比
# だけ保つため、Retina の 2x にあたる 36px で作る（32px だと拡大されてぼやける）。
tray_size=36
# グリフの周りに残す余白（px）。0 にすると端が切れて見えるため、上下左右に少しだけ残す。
tray_margin=1

for tool in rsvg-convert magick; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "Missing required tool: $tool" >&2
    exit 1
  fi
done
if ! xcrun --find actool >/dev/null 2>&1; then
  echo "Missing required tool: actool (install Xcode)" >&2
  exit 1
fi

# mark.svg の塗り（黒）を各アピアランス用の色へ差し替えて .icon のレイヤーを作る。
generate_mark_layer() {
  local out="$1" color="$2"
  {
    echo "<!-- Generated by scripts/generate-icons.sh from $mark_svg. Do not edit. -->"
    sed "s/fill=\"#000000\"/fill=\"$color\"/" "$mark_svg"
  } > "$out"
  # 置換できていなければ（マスターの書き方が変わった等）色が黒のままになり、ダークで沈む。
  if ! grep -q "fill=\"$color\"" "$out"; then
    echo "Failed to apply $color to $out (does $mark_svg still use fill=\"#000000\"?)" >&2
    exit 1
  fi
}

echo "Generating the stroke layers from $mark_svg"
generate_mark_layer "$icon_master/Assets/mark-ink.svg" "$ink_color"
generate_mark_layer "$icon_master/Assets/mark-ink-on-dark.svg" "$ink_on_dark_color"

echo "Generating $generated_dir from $icon_master"
rm -rf "$generated_dir"
mkdir -p "$generated_dir"
# actool は .icon から Tahoe 用の Assets.car と旧 macOS 用の .icns を同時に書き出す。
# .icns を ictool で直接書き出すと Tahoe 規定の余白が入らず大きすぎる見た目になるため、
# 必ず actool 経由で作る。
xcrun actool "$icon_master" --compile "$generated_dir" \
  --output-format human-readable-text --notices --warnings --errors \
  --output-partial-info-plist /dev/null \
  --app-icon openshoki --include-all-app-icons \
  --enable-on-demand-resources NO --development-region en \
  --target-device mac --minimum-deployment-target 13.0 --platform macosx

echo "Generating $tray_png from $mark_svg"
tmp_dir="$(mktemp -d -t openshoki-icons-XXXXXX)"
trap 'rm -rf "$tmp_dir"' EXIT
tmp_png="$tmp_dir/mark.png"
rsvg-convert -w 1024 -h 1024 "$mark_svg" -o "$tmp_png"
# 余白をトリムしてから 36x36 の中へ収める（縦横どちらが長くてもはみ出させない）。RGB は黒のまま
# 出す: 待機中は template 画像としてアルファだけが使われ、録音中は Rust 側（`tinted_glyph`）が
# 塗り替えるため、素材の色は問わない。形式は 8bit RGBA（`decode_rgba_png` が要求する）。
magick "$tmp_png" -trim +repage \
  -resize "$((tray_size - tray_margin * 2))x$((tray_size - tray_margin * 2))" \
  -background none -gravity center -extent "${tray_size}x${tray_size}" \
  -define png:color-type=6 -strip "$tray_png"

echo "Done:"
ls -1 "$generated_dir" | sed 's/^/  /'
echo "  $tray_png ($(magick identify -format '%wx%h %[bit-depth]bit %[channels]' "$tray_png"))"
